### PR TITLE
Newlogo for the website

### PR DESCRIPTION
**Pull request by Zubaida0113**
Hi @jahnvisahni31, I know it took me a while to publish the branch as it was an unknown territory for me to work with APIs and all, but I figured it out. Thanks for having patience with me. Also, I have made some changes to the files in the app folder as it was throwing errors while running the npm run build command.

### CODE REVIEW

**Comment by powerstone666** [comment]
could you provide a video or screenshots with changes and also try to solve conflicts use npm run build if conflicts exists then I cannot merge the pr

**Comment by jahnvisahni31** [comment]
Conflicting files
app/front-navbar.tsx
app/support/page.tsx

**Comment by Zubaida0113** [comment]
app/support/page.tsx In this case, the build fails to compile if an apostrophe is used and the site isn't deployed; it works fine without it. So please check this issue once from your side.
Screenshot (469)

**Comment by powerstone666** [comment]
it will fail again in deployment unless the build is successful and ur branch is up to date

**Comment by Zubaida0113** [comment]
app/support/page.tsx this  issue is fixed

**Comment by powerstone666** [comment]
still it has conflicts i guess now its due to commits try to close and open new pr then re push the code

**Pull request merged**
