### PR TITLE
[Feature]  Auth added using clerkjs

### PR DESCRIPTION
**Pull request by PrayanshParmar**
Issue (#52 )

Updated auth for guest user now both type of user can access workspace

with logged in users. 
image

with guest user
image

Updated Readme and added an example env file 
image

Other things will be same you can view PR (#58 ).                                                                                                                                      Most important that you have to setup clerk, then only you can put this in production if you want help to setup clerk I am ready to help

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
This Edge Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: EDGE_FUNCTION_INVOCATION_FAILED
ID: bom1::r7822-1728568569889-3dd66ed0205a

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/EDGE_FUNCTION_INVOCATION_FAILED) and [check the logs](https://design-deck-git-fork-prayanshparmar-feature-dcc50f-jahnvisahni.vercel.app/_logs?requestId=bom1::r7822-1728568569889-3dd66ed0205a).

it is showing this

**Comment by PrayanshParmar** [comment]
@jahnvisahni31 I have build the app successfully in local environment, please share the vercel deployment logs. So I can identify the issue. also you have to setup clerk js for production https://clerk.com/docs/deployments/overview

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/70/conflicts) or the  to resolve conflicts.
Conflicting files
app/front-navbar.tsx
app/layout.tsx

**Comment by ShubhamKadam098** [comment]
Any updates?

**Comment by PrayanshParmar** [comment]
No, I would like to withdraw my PR.

**Pull request closed without merging**
