### PR TITLE
Added google translator

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #176 
I have added google translator to it !! which is changing the full website language!!

https://github.com/user-attachments/assets/6fa50cc4-660a-4c5f-aa73-3343c69511e7

image

in video its not showing options block but when you click on select language it will show you many option as shown in SS

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
Conflicting files
app/front-navbar.tsx

**Comment by Sawan-Kushwah** [comment]
@jahnvisahni31 resolved the conflicts !!
please review and merge it

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/181/conflicts) or the  to resolve conflicts.
Conflicting files
app/front-navbar.tsx
again its showing this

**Comment by Sawan-Kushwah** [comment]
@jahnvisahni31 resolved conflicts !

**Pull request merged**
