### PR TITLE
AddedTerms of Use (ToU) page to the website #103

### PR DESCRIPTION
**Pull request by Zaki2409**
This PR addresses Feature #103

I have created a **Terms of Use** page in a Next.js application with the following features:

1. **Imports**:  I have brought in components for layout and metadata handling.

2. **Metadata**: I have set the page title and description for better search engine visibility.

3. **Main Component**: The `TermsOfUse` function displays the content of the Terms of Use page.

4. **Layout and Style**: The page is organized in a styled container with headings and paragraphs for clarity.

5. **Content**: It covers key topics like user responsibilities, intellectual property, and contact info.

6. **Navigation**: A button at the bottom allows users to return to the home page, enhancing navigation.

Vedio: 

https://github.com/user-attachments/assets/911ca7a7-9f37-4d11-9bf9-27e5a29de748

Screenshot:

Screenshot (48)

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
Failed to compile.
./app/terms_of_use/page.tsx
60:267  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
./app/workspace/page.tsx
260:29  Warning: The ref value 'fabricRef.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'fabricRef.current' to a variable inside the effect, and use that variable in the cleanup function.  react-hooks/exhaustive-deps
268:6  Warning: React Hook useEffect has missing dependencies: 'deleteShapeFromStorage', 'redo', 'syncShapeInStorage', and 'undo'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
./components/comments/PinnedThread.tsx
51:5  Warning: React Hook useMemo has an unnecessary dependency: 'thread.comments.length'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps
100:5  Warning: React Hook useMemo has missing dependencies: 'darkMode', 'onFocus', 'props', 'randomAvatar', and 'thread'. Either include them or remove the dependency array. If 'onFocus' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Error: Command "npm run build" exited with 1 it shows these error please check

**Comment by Zaki2409** [comment]
understood !! let me fix it .

**Comment by Zaki2409** [comment]
Changes made :
 Escaped all unescaped apostrophes (') as &apos;
 
 compilation successful.
 
DDbuild

**Comment by Zaki2409** [comment]
Hi @jahnvisahni31,

could you please review it again? I've addressed the compilation errors and would appreciate your feedback.

Thank you!!

**Pull request merged**
