### PR TITLE
Added login/signup frontend + backend

### LINKED ISSUE #28: Adding a login and signup page
**Is your feature request related to a problem? Please describe.**
As the app contains option for login and signup, but currently it dont have those pages, so i want to implement those pages

**Describe the solution you'd like**
I wanted to design and add login and signup page

**Additional context**
Screenshot 2024-10-04 201129

### PR DESCRIPTION
**Pull request by Sourabh782**
Closes #28 

1. implemented backend routes for login, logout and signup
2. designed frontend for login and signup page
3. implemented context for global access of user's state across whole site 

https://github.com/user-attachments/assets/84b24881-5841-4469-9707-7bff523b4dfd

### CODE REVIEW

**Comment by Sourabh782** [comment]
@jahnvisahni31 can you please check it? i have implemented all the changes

**Comment by jahnvisahni31** [comment]
Failed to compile.
./app/front-navbar.tsx
Error: 
  x Unexpected token `Navbar`. Expected jsx identifier
    ,-[/vercel/path0/app/front-navbar.tsx:59:1]

error

**Comment by jahnvisahni31** [comment]
make sure to do npm run build before pushing

**Comment by Sourabh782** [comment]
> make sure to do npm run build before pushing

actually @jahnvisahni31 ut current  ./app/front-navbar have some issue can u see this files code please

**Comment by Sourabh782** [comment]
> Failed to compile. ./app/front-navbar.tsx Error: x Unexpected token `Navbar`. Expected jsx identifier ,-[/vercel/path0/app/front-navbar.tsx:59:1]
> 
> error

can u check line no. 49 and 186

**Comment by Sourabh782** [comment]
@jahnvisahni31 please check now, i have fixed the issues and runed npm run build before pushing :
image

**Comment by Sourabh782** [comment]
Hello @jahnvisahni31 can you check this pr?

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/195/conflicts) or the  to resolve conflicts.
Conflicting files
app/front-navbar.tsx
it showing this only that's why unable to merge

**Comment by Sourabh782** [comment]
> This branch has conflicts that must be resolved Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/195/conflicts) or the to resolve conflicts. Conflicting files app/front-navbar.tsx it showing this only that's why unable to merge

resolved conflicts

**Comment by jahnvisahni31** [comment]
image
now this error

**Comment by Sourabh782** [comment]
> image now this error

image

**Comment by jahnvisahni31** [comment]
image
i guess it's because of prisma

**Comment by Sourabh782** [comment]
> image i guess it's because of prisma

As in line 678, can u add prisma generate command at build command?

**Comment by Sourabh782** [comment]
Lemme check it

**Comment by Sourabh782** [comment]
hey @jahnvisahni31 its deploying fine
image

Just add this to your build command: 
"prisma generate && next build"

**Comment by Sourabh782** [comment]
Hey @jahnvisahni31 thanks for merging it but considering its frontend+ backend can you increase level of issue?

**Comment by jahnvisahni31** [comment]
okay will give level 2

**Comment by Sourabh782** [comment]
> okay will give level 2

Thanks really appreciated 😊

**Pull request merged**
