### PR TITLE
added the home page

### PR DESCRIPTION
**Pull request by unknown91tech**
Added the home page and did some minor changes , change the path of the editor to /workspace and also added the dark theme button on the home page

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
#10 done and completed successfully

**Comment by jahnvisahni31** [comment]
if necessary you could make changes to that
image

**Comment by unknown91tech** [comment]
@jahnvisahni31 can you explain what changes?

**Comment by unknown91tech** [comment]
And also can I add the authencation signup and sign in page . If yes can you create that issue and assign it to me?

**Comment by jahnvisahni31** [comment]
Make sure to remove this columns rather than add features on this you can ahead with the feature part i assign thi login and authentication to another one

**Comment by jahnvisahni31** [comment]
and add a  new pr

**Pull request merged**
