### PR TITLE
🚀 Automate Connections with GitHub Actions!

### LINKED ISSUE #213: 🚀 Automate Connections with GitHub Actions!
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label @jahnvisahni31

### PR DESCRIPTION
**Pull request by amiya-cyber**
Closes #213 

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive ! @jahnvisahni31 

Note: please Add all the labels level3 and assign me to this PR !!

### CODE REVIEW

**Comment by Rakshit-gen** [comment]
You tagged the wrong person

**Comment by amiya-cyber** [comment]
Really sorry @jahnvisahni31

**Comment by amiya-cyber** [comment]
I have changed it can you just review it @jahnvisahni31

**Comment by amiya-cyber** [comment]
Hello @jahnvisahni31 can you add level 3 label as I created the entire workflow by adding 3 new files and also gssoc ext is going to end in 2 days

**Comment by amiya-cyber** [comment]
You have not added any of the labels to the pr @jahnvisahni31 add all the labels

**Review by MastanSayyad — COMMENTED** [review]
Multiple workflows in one PR = level 2, Approved!

@jahnvisahni31 please add me as a collaborator so that I can fix the labelings

**Comment by jahnvisahni31** [comment]
@MastanSayyad  please check added

**Pull request merged**
