### PR TITLE
#52 Feature added auth using clerkjs

### PR DESCRIPTION
**Pull request by PrayanshParmar**
These are the changes I have made.
1. I have added clerkjs Signup and Signin page, with third party auth GitHub, and Google.
image
image

2. I have replaced signin, signup, and user button with clerk button, Clerk user button give full acces to user to customize there profile and logout their session.
image
image

3. I have added a example environment variable file, this help developers to easily setup project.
image                                                         

Most important part is that you have to setup clerk js with your account, then only this project will work if you need guidence how to setup clerk dashborad then tell me.

### CODE REVIEW

**Comment by PrayanshParmar** [comment]
Feaature updated #52

**Comment by jahnvisahni31** [comment]
please make sure to add the in as guest feature also 
if someone doesnt want to add authentication they can use as guest

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/58/conflicts) or the  to resolve conflicts.
Conflicting files
components/Navbar.tsx

**Comment by PrayanshParmar** [comment]
@jahnvisahni31 okay I will make all routes public then.

**Comment by PrayanshParmar** [comment]
@jahnvisahni31  I am closing this PR and creating a new PR by updating code for guest user.

**Pull request closed without merging**
