### PR TITLE
fixed the open-menu in light mode

### PR DESCRIPTION
**Pull request by unknown91tech**
@jahnvisahni31 I have fixed the bug , here are some screenshots 

image

image

Can you review it an tell me if there are any changes that are to be made

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/146/conflicts) or the  to resolve conflicts.
Conflicting files
app/front-navbar.tsx

**Comment by unknown91tech** [comment]
@jahnvisahni31 does this still have conflicts ??

**Comment by unknown91tech** [comment]
@jahnvisahni31 I have added the latest merged pr which was giving the conflict

**Comment by powerstone666** [comment]
use npm run build and check for conflicts if any available I'm unable to merge your pr...!

**Comment by powerstone666** [comment]
it has conflicts solve the issues....ill merge it

**Comment by unknown91tech** [comment]
yeah will solve it in sometime

**Comment by powerstone666** [comment]
try to re push

**Comment by unknown91tech** [comment]
Can I create a new pr

**Comment by powerstone666** [comment]
sure i'll merge it

**Pull request closed without merging**
