### PR TITLE
Notification is working 

### PR DESCRIPTION
**Pull request by Aditya90456**
Notification is working @jahnvisahni31

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
image
please solve this error

**Comment by Aditya90456** [comment]
ok I'll try

**Comment by Aditya90456** [comment]
I'll give you tomorrow evening @jahnvisahni31

**Review by Aditya90456 — COMMENTED** [review]
fix

**Comment by jahnvisahni31** [comment]
Error while parsing config file: "/vercel/path0/package-lock.json"
./app/front-navbar.tsx
Error: 
  x Expression expected
    ,-[/vercel/path0/app/front-navbar.tsx:56:1]
    
please check this error
and make sure to do npm run build before submitting

**Comment by jahnvisahni31** [comment]
could you please update the repo with latest code? package.json is different that why creating an error and then do npm run build  
let me know if that works for you

**Comment by Aditya90456** [comment]
ok I'll do @jahnvisahni31

**Comment by Aditya90456** [comment]
missing handleresize function how I implement that maam ? @jahnvisahni31

**Review by Aditya90456 — COMMENTED** [review]
fix

**Comment by jahnvisahni31** [comment]
67 |         return () => window.removeEventListener('resize', handleResize);
 68 |       }  )};
 69 |     
 70 | ,->   return (
 71 | `->     <Navbar isBordered className="bg-background">
 72 |           <NavbarContent justify="start">
 73 |             <NavbarBrand className="mr-4">
 74 |               <p className="font-bold text-inherit">DesignDesk</p>
    `----
  x Unexpected token `Navbar`. Expected jsx identifier
    ,-[/vercel/path0/app/front-navbar.tsx:68:1]
 68 |   }  )};
 69 | 
 70 |   return (
 71 |     <Navbar isBordered className="bg-background">
    :      ^^^^^^
 72 |       <NavbarContent justify="start">
 73 |         <NavbarBrand className="mr-4">
 74 |           <p className="font-bold text-inherit">DesignDesk</p>
error in these lines in ./app/front-navbar.tsx

**Comment by jahnvisahni31** [comment]
could you please update the repo with latest code? package.json is different that why creating an error and then do npm run build
let me know if that works for you

**Review by Aditya90456 — COMMENTED** [review]
please check @jahnvisahni31

**Pull request merged**
