### PR TITLE
FAQ section Design

### PR DESCRIPTION
**Pull request by dev129**
### Pull Request: Implement FAQ Section for Improved SEO

**Related Issue:** #172 

#### Description
This PR introduces a new FAQ section designed to enhance SEO performance. The implementation is fully responsive and interactive, ensuring a seamless user experience across devices. Additionally, the FAQ section supports both dark and light mode to accommodate user preferences.

#### Changes Made
- Added a responsive FAQ section.
- Implemented interactive features (e.g., expandable/collapsible answers).
- Integrated light and dark mode support.
- Optimized for SEO with structured data markup.

#### How to Test
1. Pull the latest changes.
2. Check the FAQ section on various devices (mobile, tablet, desktop).
3. Toggle between dark and light mode to ensure proper functionality.
4. Verify SEO improvements through a structured data testing tool.

#### Additional Notes
- Please review the responsiveness on different screen sizes.
- Feedback on SEO optimization is welcome.

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/209/conflicts) or the  to resolve conflicts.
Conflicting files
app/faq/page.tsx

**Comment by dev129** [comment]
Hi @jahnvisahni31 , merge conflict is solved.

**Comment by dev129** [comment]
Hi @jahnvisahni31 , please check if any issue still persists.

**Comment by dev129** [comment]
Hi @jahnvisahni31 , I have solved merge conflict please review my code and let me know if any further change is needed.

**Comment by jahnvisahni31** [comment]
it shows error
image
this is the error please check

**Pull request closed without merging**
