### PR TITLE
Added Searchbar in FAQ's and fixed the Navbar issue- Unexpected Navbar

### PR DESCRIPTION
**Pull request by sandeepmaddheshiya**
#### Changes Made
- Added Search bar to FAQ's Section
### After making changes:

https://github.com/user-attachments/assets/53faed7c-77fc-4502-aee4-d1eae9ad9c3b

**Note**: This changes doesn't disturbs the previous functionalities.

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
Conflicting files
app/front-navbar.tsx

**Comment by sandeepmaddheshiya** [comment]
Ok I'll resolve it by EOD.

**Review by sandeepmaddheshiya — COMMENTED** [review]
Resolved Conflicts

**Comment by jahnvisahni31** [comment]
image
error

**Comment by sandeepmaddheshiya** [comment]
@jahnvisahni31 yeah i was also facing the same issue that's why i've changed that but due to conflicts i've revert that changes in front-navbar

**Comment by jahnvisahni31** [comment]
someone has also get the changes approved

**Comment by sandeepmaddheshiya** [comment]
It was already in the main , so i reverted to the main (due to conflicts)

**Comment by jahnvisahni31** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/jahnvisahni31/DesignDeck/pull/182/conflicts) or the  to resolve conflicts.
Conflicting files
app/faq/page.tsx

**Pull request closed without merging**
