### PR TITLE
enhanced ui fixed footer and header ui and fix error 404 page

### PR DESCRIPTION
**Pull request by abhishekpanthee**
enhanced ui fixed footer and header ui and fix error 404 page

https://github.com/user-attachments/assets/c5fba3c9-0406-46de-ab4c-8f2095f33827

### CODE REVIEW

**Comment by jahnvisahni31** [comment]
it shows error
./app/not-found.tsx
8:53  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
8:74  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
9:7  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

**Comment by abhishekpanthee** [comment]
Okay i will fix that thanks for  the info i will  push stable build

**Comment by jahnvisahni31** [comment]
Conflicting files
app/App.tsx
components/ui/ThemeSwitcher.tsx please check these

**Comment by abhishekpanthee** [comment]
yup will  resolve the merge conflicts

**Pull request closed without merging**
